version: 0.2

phases: 
  install:
    runtime-versions:
      java: openjdk11

  build:
    commands:
      - java -version
      - mvn install
  
artifacts:
  files:
    - 'target/demo1.war'
